version: '3.8'
services:
  frontend:
    container_name: frontend
    image: wdennington/5000_templates:latest
    build: ./5000_templates
    ports:
    - target: 5000
      published: 5000
    environment: 
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 5
  name_class:
    container_name: name_class
    image: wdennington/5001_name_class:latest
    build: ./5001_name_class
  stats:
    container_name: stats
    image: wdennington/5002_stats:latest
    build: ./5002_stats
  character:
    container_name: character
    image: wdennington/5003_character:latest
    build: ./5003_character
