---
- name: "Install Dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
- name: "Get docker apt key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add docker apt repo"
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present
- name: "Install Dependencies"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: "add user to docker group"
  ansible.builtin.user:
    name: cheif
    groups: docker
    append: yes

- name: Install docker with pip
  pip:
    name: docker
    executable: pip3
