---
- name: Add worker to Swarm
  docker_swarm:
    state: join
    advertise_addr: 10.154.0.12
    join_token: "{{ hostvars['10.154.0.7']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ '10.154.0.7' ]