---
- name: Add worker to Swarm
  docker_swarm:
    state: join
    advertise_addr: swarm-worker-bee, swarm-worker-a
    join_token: "{{ hostvars['swarm-master']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-master' ]